import "./globals.css";
import Header from '../components/header'; // Import the Header component

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* Add the Header component here */}
        <Header />
        
        {/* Render the children */}
        {children}
      </body>
    </html>
  );
}
